on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

env:
  # renovate: datasource=github-tags depName=golangci-lint lookupName=golangci/golangci-lint
  GOLANGCI_LINT_VERSION: v2.4.0

jobs:
  test:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - run: go vet ./...
      - run: go test ./...

  golangci:
    name: lint
    #if: github.event_name == 'pull_request'
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      # https://github.com/golangci/golangci-lint-action
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: "${{ env.GOLANGCI_LINT_VERSION }}"
          args: --timeout=5m --tests=false ./...
